### ISSUE TITLE
Need encapsulation of Execute

### ISSUE THREAD

**Issue by kolxo** [iraycd/odoo-xmlrpc-ts#1]
First of all, thanks for your work !

For moment, execute is a private method of your client.
But if you need to execute a call event like "send_request" to send an email, you can't.

You've mapped the CRUD events, but you could also "open" execute for other purposes.

**Comment by iraycd** [comment]
Ah, I understand your point! You're absolutely right.

**Comment by iraycd** [comment]
Resolved from v1.1.0
